apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: webtest1-httproute
  annotations:
    konghq.com/strip-path: 'true'
spec:
  parentRefs:
  - name: kong
  hostnames:
  - webtest1.kuberneteslabthailand.com
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: webtest1
      kind: Service
      port: 80