apiVersion: apps/v1
kind: Deployment
metadata:
  name: webtest
  labels:
    name: web
    owner: Praparn_L
    version: "1.0"
    module: WebServer
    environment: development
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      name: web
      owner: Praparn_L
      version: "1.0"
      module: WebServer
      environment: development
  template:
    metadata:
      labels:
        name: web
        owner: Praparn_L
        version: "1.0"
        module: WebServer
        environment: development
    spec:
      containers:
        - name: webtest
          image: registry.k8s.io/etcd:3.5.1-0
          command: [ "/usr/local/bin/etcd", "--data-dir",  "/var/lib/etcd", "--listen-client-urls", "http://0.0.0.0:2379", "--advertise-client-urls", "http://127.0.0.1:2379", "--log-level", "debug"]
          ports:
          - containerPort: 2379
            protocol: TCP
          readinessProbe:
            grpc:
              port: 2379
            initialDelaySeconds: 15
            periodSeconds: 5
          livenessProbe:
            grpc:
              port: 2379
            initialDelaySeconds: 15
            periodSeconds: 15
          startupProbe:
            grpc:
              port: 2379
            successThreshold: 1
            failureThreshold: 10
            periodSeconds: 30