apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: aws-ebs-pvc
spec:
   accessModes:
      - ReadWriteOncePod
   resources:
      requests:
         storage: 5Gi
   storageClassName: ebs-sc