apiVersion: v1
kind: Namespace
metadata:
  name: sample-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: httphandler
  name: httphandler
  namespace: sample-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httphandler
  template:
    metadata:
      labels:
        app: httphandler
    spec:
      containers:
      - name: badhttphandler
        image: public.ecr.aws/k9t3d5o9/badhttphandler:multistage
        ports:
        - containerPort: 8080        
---
apiVersion: v1
kind: Service
metadata:
  name: httphandler
  namespace: sample-app
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: httphandler
---
apiVersion: v1
kind: Pod
metadata:
  name: curl
  namespace: sample-app  
spec:
  containers:
  - name: curl
    image: curlimages/curl 
    command: [ "tail","-f","/dev/null" ]
---